### ISSUE TITLE
panic: runtime error: index out of range in function 'concat'

### ISSUE THREAD

**Issue by vdubc** [yuin/gopher-lua#187]
1.What version of GopherLua are you using? : 
```bash
192-168-0-110:gopher-lua sva$ git rev-parse HEAD
ca850f594eaafa5468da2bd53b865e4ee55be18b

```
2.What version of Go are you using? : 
```bash
192-168-0-110:luafail sva$ go version
go version go1.10.3 darwin/amd64
```

3.What operating system and processor architecture are you using? :
```bash
192-168-0-110:luafail sva$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.13.5
BuildVersion:   17F77
```

4.What did you do? :
```go
package f_test

import (
    "testing"

    "github.com/yuin/gopher-lua"
)

func TestFail(t *testing.T) {
    funcStr := `inspect = require("inspect")

local function Main()
    local array = {'{', '"', 'b', 'o', 'd', 'y', '"', ':', '"', 'b', 'o', 'd', 'y', '"', ',', '"', 'a', 'r', 'r', 'a',
    'y', '"', ':', '[', ']', ',', '"', 'd', 'e', 'c', 'k', '"', ':', '[', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"',
    '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'l', 'e', 'a', 'v', 'e', 's', '"', ',', '"', 'v', 'a', 'l',
    'u', 'e', '"', ':', '"', 'Q', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"',
    's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'l', 'e', 'a', 'v', 'e',
    's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '9', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"',
    ':', '9', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':',
    '"', 'h', 'e', 'a', 'r', 't', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '9', '"', ',', '"', 'w',
    'e', 'i', 'g', 'h', 't', '"', ':', '9', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"',
    's', 'u', 'i', 't', '"', ':', '"', 'a', 'c', 'o', 'r', 'n', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':',
    '"', '1', '0', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i', 'g',
    'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'a', 'c', 'o', 'r', 'n', 's', '"', ',',
    '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', 'A', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '1',
    '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'a',
    'c', 'o', 'r', 'n', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '5', '"', ',', '"', 'w', 'e', 'i',
    'g', 'h', 't', '"', ':', '5', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u',
    'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '8', '"',
    ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '8', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1',
    '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e',
    '"', ':', '"', 'Q', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i',
    'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'h', 'e', 'a', 'r', 't', 's', '"',
    ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '6', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '6',
    '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'h',
    'e', 'a', 'r', 't', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', 'J', '"', ',', '"', 'w', 'e', 'i',
    'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's',
    'u', 'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', 'A',
    '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '1', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':',
    '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'l', 'e', 'a', 'v', 'e', 's', '"', ',', '"', 'v', 'a',
    'l', 'u', 'e', '"', ':', '"', '3', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '3', '}', ',', '{', '"',
    's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'a', 'c', 'o', 'r', 'n',
    's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '8', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"',
    ':', '8', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':',
    '"', 'l', 'e', 'a', 'v', 'e', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', 'J', '"', ',', '"', 'w',
    'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',',
    '"', 's', 'u', 'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':',
    '"', '2', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '2', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"',
    ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a',
    'l', 'u', 'e', '"', ':', '"', '9', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '9', '}', ',', '{', '"',
    's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's',
    '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '4', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':',
    '4', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"',
    'h', 'e', 'a', 'r', 't', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '8', '"', ',', '"', 'w', 'e',
    'i', 'g', 'h', 't', '"', ':', '8', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's',
    'u', 'i', 't', '"', ':', '"', 'h', 'e', 'a', 'r', 't', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"',
    'A', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '1', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"',
    ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'h', 'e', 'a', 'r', 't', 's', '"', ',', '"', 'v',
    'a', 'l', 'u', 'e', '"', ':', '"', '2', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '2', '}', ',', '{',
    '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'a', 'c', 'o', 'r',
    'n', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '4', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't',
    '"', ':', '4', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"',
    ':', '"', 'h', 'e', 'a', 'r', 't', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '3', '"', ',', '"',
    'w', 'e', 'i', 'g', 'h', 't', '"', ':', '3', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',',
    '"', 's', 'u', 'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':',
    '"', 'J', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i', 'g', 'n',
    '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v',
    'a', 'l', 'u', 'e', '"', ':', '"', 'K', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',',
    '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'h', 'e', 'a',
    'r', 't', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '7', '"', ',', '"', 'w', 'e', 'i', 'g', 'h',
    't', '"', ':', '7', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't',
    '"', ':', '"', 'a', 'c', 'o', 'r', 'n', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', 'K', '"', ',',
    '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1',
    '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e',
    '"', ':', '"', '3', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '3', '}', ',', '{', '"', 's', 'i', 'g',
    'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'l', 'e', 'a', 'v', 'e', 's', '"', ',',
    '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '7', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '7', '}',
    ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'h', 'e',
    'a', 'r', 't', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '1', '0', '"', ',', '"', 'w', 'e', 'i',
    'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's',
    'u', 'i', 't', '"', ':', '"', 'h', 'e', 'a', 'r', 't', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"',
    'K', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"',
    ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'l', 'e', 'a', 'v', 'e', 's', '"', ',', '"', 'v',
    'a', 'l', 'u', 'e', '"', ':', '"', 'A', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '1', '}', ',',
    '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'h', 'e', 'a',
    'r', 't', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '5', '"', ',', '"', 'w', 'e', 'i', 'g', 'h',
    't', '"', ':', '5', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't',
    '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '6', '"', ',', '"',
    'w', 'e', 'i', 'g', 'h', 't', '"', ':', '6', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',',
    '"', 's', 'u', 'i', 't', '"', ':', '"', 'a', 'c', 'o', 'r', 'n', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"',
    ':', '"', 'Q', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i', 'g',
    'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'h', 'e', 'a', 'r', 't', 's', '"', ',',
    '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '4', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '4', '}',
    ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'l', 'e',
    'a', 'v', 'e', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '4', '"', ',', '"', 'w', 'e', 'i', 'g',
    'h', 't', '"', ':', '4', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i',
    't', '"', ':', '"', 'l', 'e', 'a', 'v', 'e', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '6', '"',
    ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '6', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1',
    '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e',
    '"', ':', '"', '7', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '7', '}', ',', '{', '"', 's', 'i', 'g',
    'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'l', 'e', 'a', 'v', 'e', 's', '"', ',',
    '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '1', '0', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1',
    '0', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"',
    'h', 'e', 'a', 'r', 't', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', 'Q', '"', ',', '"', 'w', 'e',
    'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"',
    's', 'u', 'i', 't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"',
    '1', '0', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i', 'g', 'n',
    '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'a', 'c', 'o', 'r', 'n', 's', '"', ',', '"',
    'v', 'a', 'l', 'u', 'e', '"', ':', '"', '9', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '9', '}', ',',
    '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'a', 'c', 'o',
    'r', 'n', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '3', '"', ',', '"', 'w', 'e', 'i', 'g', 'h',
    't', '"', ':', '3', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't',
    '"', ':', '"', 'a', 'c', 'o', 'r', 'n', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '7', '"', ',',
    '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '7', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"',
    ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'l', 'e', 'a', 'v', 'e', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e',
    '"', ':', '"', '2', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '2', '}', ',', '{', '"', 's', 'i', 'g',
    'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'a', 'c', 'o', 'r', 'n', 's', '"', ',',
    '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '2', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '2', '}',
    ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'l', 'e',
    'a', 'v', 'e', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '5', '"', ',', '"', 'w', 'e', 'i', 'g',
    'h', 't', '"', ':', '5', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i',
    't', '"', ':', '"', 'b', 'e', 'l', 'l', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '5', '"', ',',
    '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '5', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"',
    ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'a', 'c', 'o', 'r', 'n', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e',
    '"', ':', '"', 'J', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1', '0', '}', ',', '{', '"', 's', 'i',
    'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"', 'l', 'e', 'a', 'v', 'e', 's', '"',
    ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', 'K', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '1',
    '0', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's', 'u', 'i', 't', '"', ':', '"',
    'a', 'c', 'o', 'r', 'n', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"', '6', '"', ',', '"', 'w', 'e',
    'i', 'g', 'h', 't', '"', ':', '6', '}', ',', '{', '"', 's', 'i', 'g', 'n', '"', ':', '"', '1', '"', ',', '"', 's',
    'u', 'i', 't', '"', ':', '"', 'l', 'e', 'a', 'v', 'e', 's', '"', ',', '"', 'v', 'a', 'l', 'u', 'e', '"', ':', '"',
    '8', '"', ',', '"', 'w', 'e', 'i', 'g', 'h', 't', '"', ':', '8', '}', ']', '}'}
    local tab = table.concat(array)
    print(inspect(tab))
    return

end

return Main(...)`

    L := lua.NewState()
    defer L.Close()
    if err := L.DoString(funcStr); err != nil {
        panic(err)
    }
}
```

5. What did you expect to see? : Should be (the same code as script)
```bash
192-168-0-110:luafail sva$ lua-5.1 test.lua 
'{"body":"body","array":[],"deck":[{"sign":"1","suit":"leaves","value":"Q","weight":10},{"sign":"1","suit":"leaves","value":"9","weight":9},{"sign":"1","suit":"hearts","value":"9","weight":9},{"sign":"1","suit":"acorns","value":"10","weight":10},{"sign":"1","suit":"acorns","value":"A","weight":11},{"sign":"1","suit":"acorns","value":"5","weight":5},{"sign":"1","suit":"bells","value":"8","weight":8},{"sign":"1","suit":"bells","value":"Q","weight":10},{"sign":"1","suit":"hearts","value":"6","weight":6},{"sign":"1","suit":"hearts","value":"J","weight":10},{"sign":"1","suit":"bells","value":"A","weight":11},{"sign":"1","suit":"leaves","value":"3","weight":3},{"sign":"1","suit":"acorns","value":"8","weight":8},{"sign":"1","suit":"leaves","value":"J","weight":10},{"sign":"1","suit":"bells","value":"2","weight":2},{"sign":"1","suit":"bells","value":"9","weight":9},{"sign":"1","suit":"bells","value":"4","weight":4},{"sign":"1","suit":"hearts","value":"8","weight":8},{"sign":"1","suit":"hearts","value":"A","weight":11},{"sign":"1","suit":"hearts","value":"2","weight":2},{"sign":"1","suit":"acorns","value":"4","weight":4},{"sign":"1","suit":"hearts","value":"3","weight":3},{"sign":"1","suit":"bells","value":"J","weight":10},{"sign":"1","suit":"bells","value":"K","weight":10},{"sign":"1","suit":"hearts","value":"7","weight":7},{"sign":"1","suit":"acorns","value":"K","weight":10},{"sign":"1","suit":"bells","value":"3","weight":3},{"sign":"1","suit":"leaves","value":"7","weight":7},{"sign":"1","suit":"hearts","value":"10","weight":10},{"sign":"1","suit":"hearts","value":"K","weight":10},{"sign":"1","suit":"leaves","value":"A","weight":11},{"sign":"1","suit":"hearts","value":"5","weight":5},{"sign":"1","suit":"bells","value":"6","weight":6},{"sign":"1","suit":"acorns","value":"Q","weight":10},{"sign":"1","suit":"hearts","value":"4","weight":4},{"sign":"1","suit":"leaves","value":"4","weight":4},{"sign":"1","suit":"leaves","value":"6","weight":6},{"sign":"1","suit":"bells","value":"7","weight":7},{"sign":"1","suit":"leaves","value":"10","weight":10},{"sign":"1","suit":"hearts","value":"Q","weight":10},{"sign":"1","suit":"bells","value":"10","weight":10},{"sign":"1","suit":"acorns","value":"9","weight":9},{"sign":"1","suit":"acorns","value":"3","weight":3},{"sign":"1","suit":"acorns","value":"7","weight":7},{"sign":"1","suit":"leaves","value":"2","weight":2},{"sign":"1","suit":"acorns","value":"2","weight":2},{"sign":"1","suit":"leaves","value":"5","weight":5},{"sign":"1","suit":"bells","value":"5","weight":5},{"sign":"1","suit":"acorns","value":"J","weight":10},{"sign":"1","suit":"leaves","value":"K","weight":10},{"sign":"1","suit":"acorns","value":"6","weight":6},{"sign":"1","suit":"leaves","value":"8","weight":8}]}'
```

6. What did you see instead? :
```bash
192-168-0-110:luafail sva$ go test -v f_test.go 
=== RUN   TestFail
--- FAIL: TestFail (0.00s)
panic: runtime error: index out of range
stack traceback:
    [G]: in function 'concat'
    <string>:124: in main chunk
    (tailcall): ?
    [G]: ? [recovered]
    panic: runtime error: index out of range
stack traceback:
    [G]: in function 'concat'
    <string>:124: in main chunk
    (tailcall): ?
    [G]: ?

goroutine 5 [running]:
testing.tRunner.func1(0xc4200a20f0)
    /usr/local/opt/go/libexec/src/testing/testing.go:742 +0x29d
panic(0x11992c0, 0xc4202a9500)
    /usr/local/opt/go/libexec/src/runtime/panic.go:502 +0x229
command-line-arguments_test.TestFail(0xc4200a20f0)
    /Users/sva/go/packages/src/own/luafail/f_test.go:144 +0xc9
testing.tRunner(0xc4200a20f0, 0x11dc160)
    /usr/local/opt/go/libexec/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
    /usr/local/opt/go/libexec/src/testing/testing.go:824 +0x2e0
FAIL    command-line-arguments  0.015s
```

**Comment by yuin** [comment]
@vdubc This is not a bug. As described in [README](https://github.com/yuin/gopher-lua#callstack--registry-size), GopherLua has a fixed registry size. This script uses many registry slots than default registry size. You can increse the registry size.

```lua
L := lua.NewState(lua.Options{
    RegistrySize:  10000,
})
```
