### ISSUE TITLE
-

### ISSUE THREAD

**Issue by zaoqi** [yuin/gopher-lua#243]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x50a93b]

goroutine 1 [running]:
github.com/yuin/gopher-lua.(*LState).PCall(0xc000086000, 0x1, 0x1, 0x0, 0x0, 0x0)
	/builds/the-language/the-language/core/pure/go/deps/src/github.com/yuin/gopher-lua/state.go:1948 +0x3b
github.com/yuin/gopher-lua.(*LState).CallByParam(0xc000086000, 0x5b9460, 0xc0000b8800, 0x1, 0x1, 0x0, 0xc00031bf10, 0x1, 0x1, 0xc00000c0a0, ...)
	/builds/the-language/the-language/core/pure/go/deps/src/github.com/yuin/gopher-lua/state.go:2024 +0xe5
lang.ComplexParse(0x573fd5, 0x9, 0x0, 0x526aca)
	/builds/the-language/the-language/core/pure/go/src/lang/lang.go:2473 +0x11b
main.main()
	/builds/the-language/the-language/core/pure/go/testmain.go:3 +0x3a
exit status 2
```

**Comment by waschik** [comment]
Could you add some source code what you did? And also add an subject to this issue instead of a hyphen?
