### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bontibon** [yuin/gopher-lua#94]
1. What version of GopherLua are you using? : 03a3065
2. What version of Go are you using? : go version go1.7.4 linux/amd64
3. What operating system and processor architecture are you using? : amd64
4. What did you do? :

```go
package main

import (
	"fmt"
	"github.com/yuin/gopher-lua"
)

func main() {
	L := lua.NewState(lua.Options{
		IncludeGoStackTrace: true,
	})
	defer L.Close()

	t := L.NewTable()
	t.RawSetString("good", L.NewFunction(func(L *lua.LState) int {
		return 0
	}))
	L.SetGlobal("t", t)

	if err := L.DoString(`return t.good()`); err != nil {
		fmt.Println(err.Error())
	} else {
		fmt.Println("> no error")
	}

	if err := L.DoString(`return t.invalid()`); err != nil {
		fmt.Println(err.Error())
	} else {
		fmt.Println("> no error")
	}
}

```

5. What did you expect to see? :

```
> no error
<string>:1: attempt to call a non-function object
stack traceback:
	<string>:1: in main chunk
	[G]: ?
```

6. What did you see instead? :

```
> no error
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
github.com/yuin/gopher-lua.(*LState).PCall.func1(0xc4200b6000, 0x587b80, 0xc42003fde0, 0x0, 0x0, 0x0)
	/home/tim/go/src/github.com/yuin/gopher-lua/state.go:1622 +0x6db
panic(0x54e320, 0xc42000a120)
	/usr/lib/go/src/runtime/panic.go:458 +0x243
github.com/yuin/gopher-lua.init.3.func27(0xc4200b6000, 0x80000001, 0xc4200ac000, 0x0)
	/home/tim/go/src/github.com/yuin/gopher-lua/vm.go:714 +0x194
github.com/yuin/gopher-lua.mainLoop(0xc4200b6000, 0xc4200ac000)
	/home/tim/go/src/github.com/yuin/gopher-lua/vm.go:31 +0xd1
github.com/yuin/gopher-lua.(*LState).callR(0xc4200b6000, 0x0, 0xffffffffffffffff, 0x0)
	/home/tim/go/src/github.com/yuin/gopher-lua/state.go:873 +0x26e
github.com/yuin/gopher-lua.(*LState).Call(0xc4200b6000, 0x0, 0xffffffffffffffff)
	/home/tim/go/src/github.com/yuin/gopher-lua/state.go:1601 +0x48
github.com/yuin/gopher-lua.(*LState).PCall(0xc4200b6000, 0x0, 0xffffffffffffffff, 0x0, 0x615300, 0xc4200be900)
	/home/tim/go/src/github.com/yuin/gopher-lua/state.go:1662 +0xe3
github.com/yuin/gopher-lua.(*LState).DoString(0xc4200b6000, 0x574f60, 0x12, 0xb, 0x0)
	/home/tim/go/src/github.com/yuin/gopher-lua/auxlib.go:403 +0xcb
main.main()
	/home/tim/x.go:28 +0x49e

stack traceback:
	<string>:1: in main chunk
	[G]: ?

```

**Comment by yuin** [comment]
Thanks for reporting this @bontibon . I've fixed that in latest commit.
